services:
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile.dev

        volumes:
            - ./:/app
            - ./var:/app/var

        environment:
            APP_ENV: dev

        command: bash
