# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    telegram.bot_token: '%env(TELEGRAM_BOT_TOKEN)%'
    telegram.chat_id: '%env(TELEGRAM_CHAT_ID)%'
    ai.api_base: '%env(AI_API_BASE)%'
    ai.api_key: '%env(AI_API_KEY)%'
    ai.model: '%env(AI_MODEL)%'
    app.job_feed_urls:
        - '%env(default::JOB_FEED_URL_1)%'
        - '%env(default::JOB_FEED_URL_2)%'
#        - '%env(default::JOB_FEED_URL_3)%'
#        - '%env(default::JOB_FEED_URL_4)%'
#        - '%env(default::JOB_FEED_URL_5)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Service\Provider\JobProviderInterface:
            tags: ['app.job_provider']

    App\:
        resource: '../src/'

    App\Command\RunPipelineCommand:
        arguments:
            $providers: !tagged_iterator app.job_provider

    App\Service\Notification\TelegramNotifier:
        arguments:
            $botToken: '%telegram.bot_token%'
            $chatId: '%telegram.chat_id%'

    App\Service\AI\AIClient:
        arguments:
            $cache: '@cache.app'
            $apiBase: '%ai.api_base%'
            $apiKey: '%ai.api_key%'
            $model: '%ai.model%'
            $systemPrompt: '%app.ai_system_prompt%'
            $knownStack: '%app.known_stack%'

    App\Service\Provider\RsFeedProvider:
        arguments:
            $feedUrls: '%app.job_feed_urls%'
        tags: ['app.job_provider']

    App\Service\Provider\SearxProvider:
        arguments:
            $baseUrl: '%env(SEARXNG_URL)%'
            $searchQueries: '%app.searx_queries%'
            $locations: '%app.job_locations%'
        tags: [ 'app.job_provider' ]

    App\Service\Processor\JobProcessor:
        arguments:
            $filterKeywords: '%app.filter_keywords%'

    App\Service\Scoring\ScoringService:
        arguments:
            $scoringConfig: '%app.scoring%'
