# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    telegram.bot_token: '%env(TELEGRAM_BOT_TOKEN)%'
    telegram.chat_id: '%env(TELEGRAM_CHAT_ID)%'
    openai.api_base: '%env(OPENAI_API_BASE)%'
    openai.api_key: '%env(OPENAI_API_KEY)%'
    openai.model: '%env(OPENAI_MODEL)%'
    app.job_feed_urls:
        - '%env(default::JOB_FEED_URL_1)%'
        - '%env(default::JOB_FEED_URL_2)%'
#        - '%env(default::JOB_FEED_URL_3)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Service\Provider\JobProviderInterface:
            tags: ['app.job_provider']

    App\:
        resource: '../src/'

    App\Command\RunPipelineCommand:
        arguments:
            $providers: !tagged_iterator app.job_provider

    App\Service\Notification\TelegramNotifier:
        arguments:
            $botToken: '%telegram.bot_token%'
            $chatId: '%telegram.chat_id%'

    App\Service\AI\OpenAIClient:
        arguments:
            $apiBase: '%openai.api_base%'
            $apiKey: '%openai.api_key%'
            $model: '%openai.model%'

    App\Service\Provider\RsFeedProvider:
        arguments:
            $feedUrls: '%app.job_feed_urls%'
        tags: ['app.job_provider']
