FROM php:8.3-cli

RUN apt-get update && apt-get install -y \
    git unzip zip curl \
    libzip-dev libxml2-dev \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install zip xml opcache

COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer

WORKDIR /app
