FROM php:8.3-cli

RUN apt-get update && apt-get install -y \
    git unzip zip curl \
    libzip-dev libxml2-dev \
    libpq-dev postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Extensions PHP (inclut PostgreSQL)
RUN docker-php-ext-install zip xml opcache pgsql pdo_pgsql

COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer

WORKDIR /app
